### ISSUE TITLE
monthly meeting?

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/MBON_phytoplankton_pigments#3]
Maybe we can set up a monthly meeting so I can stay updated on the status of this project? My availability: [bit.ly/ty-calendar](https://bit.ly/ty-calendar)

**Comment by sebastiandig** [comment]
Hi @7yl4r ,
Yes, we should. I can't access the calendar.  It brings to a `401 error` page, but I think we are both pretty open. So if you just set a day and time, we'll be there (after 10 am).

**Comment by 7yl4r** [comment]
Weird that GitHub inserted itself into that link; I've fixed it. But anyway: I have sent an invite for next Monday (July 25th) 3-4 EST. Let me know if that does not work, else close this and I look forward to chatting then! 👍

**Comment by sebastiandig** [comment]
Great, see you then!
